export {
  ADMIN_CAPABILITY_MANAGE_ADMINS,
  ADMIN_CAPABILITY_MANAGE_STAFF,
  ADMIN_CAPABILITY_MANAGE_ROSTER,
  ADMIN_CAPABILITY_MANAGE_COMMUNICATIONS,
  ALL_ADMIN_CAPABILITIES,
  type AdminCapability,
} from "@chemisttasker/shared-core";
