/**
 * Admin capability constants
 */
export const ADMIN_CAPABILITY_MANAGE_ADMINS = "MANAGE_ADMINS";
export const ADMIN_CAPABILITY_MANAGE_STAFF = "MANAGE_STAFF";
export const ADMIN_CAPABILITY_MANAGE_ROSTER = "MANAGE_ROSTER";
export const ADMIN_CAPABILITY_MANAGE_COMMUNICATIONS = "MANAGE_COMMUNICATIONS";

export type AdminCapability =
    | typeof ADMIN_CAPABILITY_MANAGE_ADMINS
    | typeof ADMIN_CAPABILITY_MANAGE_STAFF
    | typeof ADMIN_CAPABILITY_MANAGE_ROSTER
    | typeof ADMIN_CAPABILITY_MANAGE_COMMUNICATIONS;

export const ALL_ADMIN_CAPABILITIES: AdminCapability[] = [
    ADMIN_CAPABILITY_MANAGE_ADMINS,
    ADMIN_CAPABILITY_MANAGE_STAFF,
    ADMIN_CAPABILITY_MANAGE_ROSTER,
    ADMIN_CAPABILITY_MANAGE_COMMUNICATIONS,
];
